/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package udesc.eso.socketClient.view;

import udesc.eso.socketClient.view.viewFactory.RequestStrategyFactory;
import udesc.eso.socketClient.view.viewStrategy.RequestStrategyProtocol;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author sonho
 */
public class HomeView extends javax.swing.JFrame {

	/**
	 * Creates new form HomeView
	 */
	public HomeView() {
		initComponents();
		btnSend.addActionListener(e -> sendRequest());
		cbEntity.addActionListener(e -> updateFieldsBasedOnEntity(cbEntity.getSelectedItem().toString()));
		cbOperation.addActionListener(e -> updateFieldsBasedOnOperation(cbOperation.getSelectedItem().toString()));
		UiHandler.setFieldsVisibility(false, txtAttr4, txtAttr5, txtAttr7);
		UiHandler.setLabelsVisibility(false, lbAttr4, lbAttr5, lbAttr6, lbAttr7);
		UiHandler.setButtonsVisibility(false, optionNo, optionYes);
		lbAttr2.setText("Cidade");
		lbAttr3.setText("Fundos");
		initImage("/guilda.jpg");
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                optionBtnGroup = new javax.swing.ButtonGroup();
                lbAddress = new javax.swing.JLabel();
                txtAddress = new javax.swing.JTextField();
                lbPort = new javax.swing.JLabel();
                txtPort = new javax.swing.JTextField();
                cbOperation = new javax.swing.JComboBox<>();
                jSeparator1 = new javax.swing.JSeparator();
                cbEntity = new javax.swing.JComboBox<>();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                txtAttr1 = new javax.swing.JTextField();
                lbAttr1 = new javax.swing.JLabel();
                lbAttr2 = new javax.swing.JLabel();
                txtAttr2 = new javax.swing.JTextField();
                lbAttr3 = new javax.swing.JLabel();
                txtAttr3 = new javax.swing.JTextField();
                txtAttr5 = new javax.swing.JTextField();
                lbAttr5 = new javax.swing.JLabel();
                lbAttr6 = new javax.swing.JLabel();
                lbAttr7 = new javax.swing.JLabel();
                txtAttr7 = new javax.swing.JTextField();
                txtAttr4 = new javax.swing.JTextField();
                lbAttr4 = new javax.swing.JLabel();
                btnSend = new javax.swing.JButton();
                optionYes = new javax.swing.JRadioButton();
                optionNo = new javax.swing.JRadioButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                taResponse = new javax.swing.JTextArea();
                jLabel4 = new javax.swing.JLabel();
                lbImage = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                lbAddress.setText("Endereço do servidor");

                lbPort.setText("Porta do servidor");

                cbOperation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Insert", "Get", "Update", "Delete", "List", "AddMember", "GetMember", "DeleteMember", "ListMember" }));

                jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

                cbEntity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Guilda", "Mago", "Guerreiro" }));

                jLabel1.setText("Operação");

                jLabel2.setText("Entidade");

                jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                jLabel3.setText("Campos");

                lbAttr1.setText("Nome");

                lbAttr2.setText("Cidade");

                lbAttr3.setText("Fundos");

                lbAttr5.setText("Arma");

                lbAttr6.setText("Escudo");

                lbAttr7.setText("Magia");

                lbAttr4.setText("Cpf");

                btnSend.setText("Enviar");
                btnSend.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnSendActionPerformed(evt);
                        }
                });

                optionBtnGroup.add(optionYes);
                optionYes.setText("Sim");

                optionBtnGroup.add(optionNo);
                optionNo.setText("Não");
                optionNo.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                optionNoActionPerformed(evt);
                        }
                });

                taResponse.setEditable(false);
                taResponse.setColumns(20);
                taResponse.setRows(5);
                jScrollPane1.setViewportView(taResponse);

                jLabel4.setText("Resposta do servidor");

                lbImage.setToolTipText("");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(68, 68, 68)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lbPort)
                                                        .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lbAddress)
                                                        .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel4)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(35, 35, 35)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(cbOperation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cbEntity, 0, 121, Short.MAX_VALUE))
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2)
                                        .addComponent(lbAttr2)
                                        .addComponent(txtAttr2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbAttr3)
                                        .addComponent(txtAttr3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbAttr4)
                                        .addComponent(txtAttr4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3)
                                        .addComponent(lbAttr1)
                                        .addComponent(txtAttr1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbAttr7)
                                        .addComponent(txtAttr7, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbAttr6)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(optionYes)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(optionNo))
                                        .addComponent(lbAttr5)
                                        .addComponent(txtAttr5, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                                .addComponent(lbImage, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbAddress)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lbPort, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cbOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(9, 9, 9)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cbEntity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(17, 17, 17)
                                                .addComponent(lbAttr1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtAttr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lbAttr2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtAttr2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lbAttr3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtAttr3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lbAttr4)
                                                .addGap(7, 7, 7)
                                                .addComponent(txtAttr4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(66, 66, 66)
                                                                .addComponent(lbAttr5)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txtAttr5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(lbAttr6)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(optionYes)
                                                                        .addComponent(optionNo))
                                                                .addGap(39, 39, 39)
                                                                .addComponent(btnSend))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(lbAttr7)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txtAttr7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(26, 26, 26)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jSeparator1)
                                .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(lbImage, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(34, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

	private void initImage(String imageSrc) {
		ImageIcon newImageIcon = new ImageIcon(getClass().getResource(imageSrc));

		lbImage.setIcon(newImageIcon);

		lbImage.revalidate();
		lbImage.repaint();
	}

	private void updateFieldsBasedOnOperation(String operation) {
		resetFormUI(true);
		switch (operation) {
			case "Insert", "Update":
				if (checkGuild()) break;
				UiHandler.setFieldsVisibility(true, txtAttr1, txtAttr2, txtAttr3, txtAttr4, txtAttr5, txtAttr7);
				UiHandler.setLabelsVisibility(true, lbAttr1, lbAttr2, lbAttr3, lbAttr4, lbAttr5, lbAttr6, lbAttr7);
				UiHandler.setButtonsVisibility(true, optionNo, optionYes);
				if (cbEntity.getSelectedItem().toString().equals("Guerreiro")) {
					UiHandler.setFieldsVisibility(false, txtAttr7);
					UiHandler.setLabelsVisibility(false, lbAttr7);
				}
				break;
			case "Get":
				if (cbEntity.getSelectedItem().toString().equals("Guilda")) {
					UiHandler.setFieldsVisibility(false, txtAttr2, txtAttr3, txtAttr4, txtAttr5, txtAttr7);
					UiHandler.setLabelsVisibility(false, lbAttr2, lbAttr3, lbAttr4, lbAttr5, lbAttr6, lbAttr7);
					UiHandler.setButtonsVisibility(false, optionNo, optionYes);
					txtAttr1.setVisible(true);
					lbAttr1.setVisible(true);
					break;
				}
				UiHandler.setFieldsVisibility(false, txtAttr1, txtAttr2, txtAttr3, txtAttr5, txtAttr7);
				UiHandler.setLabelsVisibility(false, lbAttr1, lbAttr2, lbAttr3, lbAttr5, lbAttr6, lbAttr7);
				UiHandler.setButtonsVisibility(false, optionNo, optionYes);
				break;

            case "Delete":
				if (cbEntity.getSelectedItem().toString().equals("Guilda")) {
					UiHandler.setFieldsVisibility(false, txtAttr2, txtAttr3, txtAttr4, txtAttr5, txtAttr7);
					UiHandler.setLabelsVisibility(false, lbAttr2, lbAttr3, lbAttr4, lbAttr5, lbAttr6, lbAttr7);
					UiHandler.setButtonsVisibility(false, optionNo, optionYes);
					break;
				}
				UiHandler.setFieldsVisibility(false, txtAttr1, txtAttr2, txtAttr3, txtAttr5, txtAttr7);
				UiHandler.setLabelsVisibility(false, lbAttr1, lbAttr2, lbAttr3, lbAttr5, lbAttr6, lbAttr7);
				UiHandler.setButtonsVisibility(false, optionNo, optionYes);
				break;
			case "List":
				resetFormUI(false);
				btnSend.setVisible(true);
				break;
			case "AddMember","GetMember","DeleteMember" :
				checkGuildEntity();
				break;
			case "ListMember":
				if (cbEntity.getSelectedItem().toString().equals("Guilda")) {
					UiHandler.setFieldsVisibility(false, txtAttr2, txtAttr3, txtAttr4, txtAttr5, txtAttr7);
					UiHandler.setLabelsVisibility(false, lbAttr2, lbAttr3, lbAttr4, lbAttr5, lbAttr6, lbAttr7);
					UiHandler.setButtonsVisibility(false, optionNo, optionYes);
					break;
				} else {
					resetFormUI(false);
					break;
				}

		}
	}

	private void checkGuildEntity() {
		if (cbEntity.getSelectedItem().toString().equals("Guilda")) {
			UiHandler.setFieldsVisibility(false, txtAttr2, txtAttr3, txtAttr5, txtAttr7);
			UiHandler.setLabelsVisibility(false, lbAttr2, lbAttr3, lbAttr5, lbAttr6, lbAttr7);
			UiHandler.setButtonsVisibility(false, optionNo, optionYes);
		} else {
			resetFormUI(false);
		}
	}

	private boolean checkGuild() {
		if (cbEntity.getSelectedItem().toString().equals("Guilda")) {
			UiHandler.setFieldsVisibility(false, txtAttr4, txtAttr5, txtAttr7);
			UiHandler.setLabelsVisibility(false, lbAttr4, lbAttr5, lbAttr6, lbAttr7);
			UiHandler.setButtonsVisibility(false, optionNo, optionYes);
			UiHandler.setFieldsVisibility(true, txtAttr1, txtAttr2, txtAttr3);
			UiHandler.setLabelsVisibility(true, lbAttr1, lbAttr2, lbAttr3);
			return true;
		}
		return false;
	}

	private void updateFieldsBasedOnEntity(String entity) {
		UiHandler.clearFields(txtAttr1, txtAttr2, txtAttr3, txtAttr4, txtAttr5, txtAttr7);
		switch (entity) {
			case "Guilda":
				if (cbOperation.getSelectedItem().toString().equals("AddMember")
					|| cbOperation.getSelectedItem().toString().equals("DeleteMember")
					|| cbOperation.getSelectedItem().toString().equals("GetMember")) {
					resetFormUI(false);
					UiHandler.setFieldsVisibility(true, txtAttr1, txtAttr4);
					UiHandler.setLabelsVisibility(true, lbAttr1, lbAttr4);
					lbAttr1.setText("Nome Guilda");
					lbAttr4.setText("Cpf membro");
					btnSend.setVisible(true);
					break;
				}
				UiHandler.setLabelsVisibility(false, lbAttr4, lbAttr5, lbAttr6, lbAttr7);
				UiHandler.setButtonsVisibility(false, optionNo, optionYes);
				UiHandler.setFieldsVisibility(true, txtAttr1, txtAttr2, txtAttr3);
				UiHandler.setLabelsVisibility(true, lbAttr1, lbAttr2, lbAttr3);
				lbAttr1.setText("Nome Guilda");
				lbAttr2.setText("Cidade");
				lbAttr3.setText("Fundos");
				lbAttr4.setText("Cpf membro");
				initImage("/guilda.jpg");
				break;
			case "Mago":
				UiHandler.setFieldsVisibility(true, txtAttr1, txtAttr2, txtAttr3, txtAttr4, txtAttr5, txtAttr7);
				UiHandler.setLabelsVisibility(true, lbAttr1, lbAttr2, lbAttr3, lbAttr4, lbAttr5, lbAttr6, lbAttr7);
				UiHandler.setButtonsVisibility(true, optionNo, optionYes);
				lbAttr1.setText("Nome Mago");
				lbAttr2.setText("Endereço");
				lbAttr3.setText("Idade");
				lbAttr5.setText("Elemento");
				lbAttr6.setText("Chapéu");
				lbAttr4.setText("Cpf");
				initImage("/mago.jpg");
				break;
			case "Guerreiro":
				UiHandler.setFieldsVisibility(true, txtAttr1, txtAttr2, txtAttr3, txtAttr4, txtAttr5);
				UiHandler.setLabelsVisibility(true, lbAttr1, lbAttr2, lbAttr3, lbAttr4, lbAttr5, lbAttr6);
				UiHandler.setButtonsVisibility(true, optionNo, optionYes);
				lbAttr1.setText("Nome Guerreiro");
				lbAttr2.setText("Endereço");
				lbAttr3.setText("Idade");
				lbAttr5.setText("Arma");
				lbAttr6.setText("Escudo");
				lbAttr4.setText("Cpf");
				txtAttr7.setVisible(false);
				lbAttr7.setVisible(false);
				initImage("/guerreiro.jpg");
				break;
		}
	}
	private void resetFormUI(Boolean visibility) {
		UiHandler.clearFields(txtAttr1, txtAttr2, txtAttr3, txtAttr4, txtAttr5, txtAttr7);
		UiHandler.setFieldsVisibility(visibility, txtAttr1, txtAttr2, txtAttr3, txtAttr4, txtAttr5, txtAttr7);
		UiHandler.setLabelsVisibility(visibility, lbAttr1, lbAttr2, lbAttr3, lbAttr4, lbAttr5, lbAttr6, lbAttr7);
		UiHandler.setButtonsVisibility(visibility, optionNo, optionYes);
		btnSend.setVisible(visibility);
	}
	private void sendRequest() {
		String serverAddress = txtAddress.getText();
		int serverPort = 3030;
		try {
			serverPort = Integer.parseInt(txtPort.getText());
		} catch (NumberFormatException exception) {
			JOptionPane.showMessageDialog(this, "Porta inválida, apenas números", "Porta inválida", JOptionPane.ERROR_MESSAGE);
		}

		try (Socket socket = new Socket(serverAddress, serverPort)) {
			taResponse.setText("");
			PrintWriter out = new PrintWriter(socket.getOutputStream(), true);
			BufferedReader in = new BufferedReader(new InputStreamReader(socket.getInputStream()));

			String messageToSend = this.createStringRequest();
			out.println(messageToSend);

			String response;
			StringBuilder fullResponse = new StringBuilder();
			while ((response = in.readLine()) != null && !response.isEmpty()) {
				fullResponse.append(response).append("\n");
			}

			taResponse.append(fullResponse.toString());

			socket.close();
		} catch (IOException e) {
			e.printStackTrace();
		}
	}

	private Boolean getOptionResult() {
		return optionYes.isSelected();
	}

	private String createStringRequest() {
		String entityType = cbEntity.getSelectedItem().toString();
		String operation = cbOperation.getSelectedItem().toString();

		Map<String, String> attributes = getAttributes();

		RequestStrategyProtocol strategy = RequestStrategyFactory.makeStrategy(entityType);

		return strategy.buildRequest(operation, attributes);
	}

	private Map<String, String> getAttributes() {
		Map<String, String> attributes = new HashMap<String, String>();
		attributes.put("nome", txtAttr1.getText());
		attributes.put("endereco", txtAttr2.getText());
		attributes.put("idade", txtAttr3.getText());
		attributes.put("cpf", txtAttr4.getText());
		attributes.put("cidade", txtAttr2.getText());
		attributes.put("fundos", txtAttr3.getText());
		attributes.put("elemento", txtAttr5.getText());
		attributes.put("chapeu", this.getOptionResult().toString());
		attributes.put("magia", txtAttr7.getText());
		attributes.put("arma", txtAttr5.getText());
		attributes.put("escudo", this.getOptionResult().toString());
		return attributes;
	}


	private void optionNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionNoActionPerformed
		// TODO add your handling code here:
        }//GEN-LAST:event_optionNoActionPerformed

        private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed

        }//GEN-LAST:event_btnSendActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new HomeView().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnSend;
        private javax.swing.JComboBox<String> cbEntity;
        private javax.swing.JComboBox<String> cbOperation;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JSeparator jSeparator1;
        private javax.swing.JLabel lbAddress;
        private javax.swing.JLabel lbAttr1;
        private javax.swing.JLabel lbAttr2;
        private javax.swing.JLabel lbAttr3;
        private javax.swing.JLabel lbAttr4;
        private javax.swing.JLabel lbAttr5;
        private javax.swing.JLabel lbAttr6;
        private javax.swing.JLabel lbAttr7;
        private javax.swing.JLabel lbImage;
        private javax.swing.JLabel lbPort;
        private javax.swing.ButtonGroup optionBtnGroup;
        private javax.swing.JRadioButton optionNo;
        private javax.swing.JRadioButton optionYes;
        private javax.swing.JTextArea taResponse;
        private javax.swing.JTextField txtAddress;
        private javax.swing.JTextField txtAttr1;
        private javax.swing.JTextField txtAttr2;
        private javax.swing.JTextField txtAttr3;
        private javax.swing.JTextField txtAttr4;
        private javax.swing.JTextField txtAttr5;
        private javax.swing.JTextField txtAttr7;
        private javax.swing.JTextField txtPort;
        // End of variables declaration//GEN-END:variables
}
